-- LNU SkillHub Supabase schema
-- Run this in Supabase Dashboard > SQL Editor.

create extension if not exists "pgcrypto";

create table if not exists public.users (
  uid uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text not null default '',
  student_id text not null default '',
  college text not null default '',
  department text not null default '',
  year_level text not null default '',
  username text not null default '',
  role text not null default 'user',
  email_verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  uid uuid primary key references auth.users(id) on delete cascade,
  profile_picture_url text not null default '',
  full_name text not null default '',
  student_id text not null default '',
  college text not null default '',
  department text not null default '',
  year_level text not null default '',
  username text not null default '',
  bio text not null default '',
  skills text[] not null default '{}',
  portfolio_gallery text[] not null default '{}',
  availability_status text not null default 'available',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null default 'LNU student',
  author_email text not null default '',
  author_department text not null default '',
  type text not null check (
    type in (
      'Artwork showcase',
      'Commission open post',
      'Service promotion',
      'Progress update',
      'Announcement'
    )
  ),
  caption text not null default '',
  media_urls text[] not null default '{}',
  media_type text not null default 'none',
  heart_count integer not null default 0 check (heart_count >= 0),
  view_count integer not null default 0 check (view_count >= 0),
  share_count integer not null default 0 check (share_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_reactions (
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null default 'heart' check (type = 'heart'),
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.post_views (
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.post_shares (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.listings (
  id int8 generated by default as identity primary key,
  title text not null default '',
  description text not null default '',
  price numeric not null default 0 check (price >= 0),
  category text not null default '',
  image_url text not null default '',
  seller_name text not null default '',
  seller_id text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists listings_created_at_idx
on public.listings (created_at desc);

create index if not exists listings_seller_id_idx
on public.listings (seller_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (
    uid,
    email,
    full_name,
    student_id,
    college,
    department,
    year_level,
    username,
    email_verified
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'student_id', ''),
    coalesce(new.raw_user_meta_data ->> 'college', ''),
    coalesce(new.raw_user_meta_data ->> 'department', ''),
    coalesce(new.raw_user_meta_data ->> 'year_level', ''),
    coalesce(new.raw_user_meta_data ->> 'username', ''),
    new.email_confirmed_at is not null
  )
  on conflict (uid) do update set
    email = excluded.email,
    full_name = excluded.full_name,
    student_id = excluded.student_id,
    college = excluded.college,
    department = excluded.department,
    year_level = excluded.year_level,
    username = excluded.username,
    email_verified = excluded.email_verified,
    updated_at = now();

  insert into public.profiles (
    uid,
    full_name,
    student_id,
    college,
    department,
    year_level,
    username
  )
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'student_id', ''),
    coalesce(new.raw_user_meta_data ->> 'college', ''),
    coalesce(new.raw_user_meta_data ->> 'department', ''),
    coalesce(new.raw_user_meta_data ->> 'year_level', ''),
    coalesce(new.raw_user_meta_data ->> 'username', '')
  )
  on conflict (uid) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.users enable row level security;
alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.post_reactions enable row level security;
alter table public.post_views enable row level security;
alter table public.post_shares enable row level security;
alter table public.listings enable row level security;

create or replace function public.is_lnu_email()
returns boolean
language sql
stable
as $$
  select auth.jwt() ->> 'email' like '%@lnu.edu.ph'
$$;

drop policy if exists "users owner access" on public.users;
create policy "users owner access"
on public.users
for all
using (public.is_lnu_email() and auth.uid() = uid)
with check (public.is_lnu_email() and auth.uid() = uid);

drop policy if exists "profiles lnu read" on public.profiles;
create policy "profiles lnu read"
on public.profiles
for select
using (public.is_lnu_email());

drop policy if exists "profiles owner write" on public.profiles;
create policy "profiles owner write"
on public.profiles
for all
using (public.is_lnu_email() and auth.uid() = uid)
with check (public.is_lnu_email() and auth.uid() = uid);

drop policy if exists "posts lnu read" on public.posts;
create policy "posts lnu read"
on public.posts
for select
using (public.is_lnu_email());

drop policy if exists "posts owner create" on public.posts;
create policy "posts owner create"
on public.posts
for insert
with check (public.is_lnu_email() and auth.uid() = author_id);

drop policy if exists "posts owner delete" on public.posts;
create policy "posts owner delete"
on public.posts
for delete
using (public.is_lnu_email() and auth.uid() = author_id);

drop policy if exists "post reactions lnu read" on public.post_reactions;
create policy "post reactions lnu read"
on public.post_reactions
for select
using (public.is_lnu_email());

drop policy if exists "post reactions owner create" on public.post_reactions;
create policy "post reactions owner create"
on public.post_reactions
for insert
with check (public.is_lnu_email() and auth.uid() = user_id);

drop policy if exists "post reactions owner delete" on public.post_reactions;
create policy "post reactions owner delete"
on public.post_reactions
for delete
using (public.is_lnu_email() and auth.uid() = user_id);

drop policy if exists "post views lnu read" on public.post_views;
create policy "post views lnu read"
on public.post_views
for select
using (public.is_lnu_email());

drop policy if exists "post views owner create" on public.post_views;
create policy "post views owner create"
on public.post_views
for insert
with check (public.is_lnu_email() and auth.uid() = user_id);

drop policy if exists "post shares lnu read" on public.post_shares;
create policy "post shares lnu read"
on public.post_shares
for select
using (public.is_lnu_email());

drop policy if exists "post shares owner create" on public.post_shares;
create policy "post shares owner create"
on public.post_shares
for insert
with check (public.is_lnu_email() and auth.uid() = user_id);

drop policy if exists "listings lnu read" on public.listings;
create policy "listings lnu read"
on public.listings
for select
using (public.is_lnu_email());

drop policy if exists "listings owner create" on public.listings;
create policy "listings owner create"
on public.listings
for insert
with check (public.is_lnu_email() and auth.uid()::text = seller_id);

drop policy if exists "listings owner update" on public.listings;
create policy "listings owner update"
on public.listings
for update
using (public.is_lnu_email() and auth.uid()::text = seller_id)
with check (public.is_lnu_email() and auth.uid()::text = seller_id);

drop policy if exists "listings owner delete" on public.listings;
create policy "listings owner delete"
on public.listings
for delete
using (public.is_lnu_email() and auth.uid()::text = seller_id);

create or replace function public.toggle_post_heart(target_post_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (
    select 1 from public.post_reactions
    where post_id = target_post_id and user_id = auth.uid()
  ) then
    delete from public.post_reactions
    where post_id = target_post_id and user_id = auth.uid();

    update public.posts
    set heart_count = greatest(heart_count - 1, 0), updated_at = now()
    where id = target_post_id;
  else
    insert into public.post_reactions (post_id, user_id)
    values (target_post_id, auth.uid());

    update public.posts
    set heart_count = heart_count + 1, updated_at = now()
    where id = target_post_id;
  end if;
end;
$$;

create or replace function public.mark_post_viewed(target_post_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.post_views (post_id, user_id)
  values (target_post_id, auth.uid())
  on conflict do nothing;

  update public.posts
  set view_count = (
    select count(*) from public.post_views where post_id = target_post_id
  ),
  updated_at = now()
  where id = target_post_id;
end;
$$;

create or replace function public.mark_post_shared(target_post_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.post_shares (post_id, user_id)
  values (target_post_id, auth.uid());

  update public.posts
  set share_count = share_count + 1, updated_at = now()
  where id = target_post_id;
end;
$$;

insert into storage.buckets (id, name, public)
values ('post-media', 'post-media', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('listing-images', 'listing-images', true)
on conflict (id) do nothing;

drop policy if exists "post media lnu read" on storage.objects;
create policy "post media lnu read"
on storage.objects
for select
using (bucket_id = 'post-media' and public.is_lnu_email());

drop policy if exists "post media owner write" on storage.objects;
create policy "post media owner write"
on storage.objects
for insert
with check (
  bucket_id = 'post-media'
  and public.is_lnu_email()
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "listing images lnu read" on storage.objects;
create policy "listing images lnu read"
on storage.objects
for select
using (bucket_id = 'listing-images' and public.is_lnu_email());

drop policy if exists "listing images owner create" on storage.objects;
create policy "listing images owner create"
on storage.objects
for insert
with check (
  bucket_id = 'listing-images'
  and public.is_lnu_email()
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "listing images owner update" on storage.objects;
create policy "listing images owner update"
on storage.objects
for update
using (
  bucket_id = 'listing-images'
  and public.is_lnu_email()
  and auth.uid()::text = (storage.foldername(name))[1]
)
with check (
  bucket_id = 'listing-images'
  and public.is_lnu_email()
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "listing images owner delete" on storage.objects;
create policy "listing images owner delete"
on storage.objects
for delete
using (
  bucket_id = 'listing-images'
  and public.is_lnu_email()
  and auth.uid()::text = (storage.foldername(name))[1]
);
